#!/bin/bash

read -p "enter username :" u
read -sp "enter password :" p
un=admin
pa=Administrator123
#u1=Developer
#p1=javapython@123
if [  $u = $un -a $p = $pa ] #-o ( $u = $u1 -a $p1 = $p )  ]
then
      echo "Authentiocaiton is succesfull"
else
	echo "authentiocation is unsuccefull"
fi

read -p "enter username :" s
read -sp "enter password :" b

u1=Developer
p1=javapython@123
if [ $s = $u1 -a $p1 = $b ]
then
      echo "Authentiocaiton is succesfull"
else
        echo "authentiocation is unsuccefull"
fi

read -p "enter the character :" c
#d=aeiouAEIOU

#if [ grep-i $c $d ]
if [ $c = a -o $c = e -o $c = i -o $c = o -o $c = u ]
	then
		echo " character is vowel"
	elif [ $c = O -o $c = A -o $c = E -o $c = I -o $c = U ]
	then
		echo " character is vowel"
	else
		echo "characeter is not vowel"
fi

read -p "enter the age :" a
if [  -z $a ]
then
	echo "enter the age:"
	
elif [ $a -le 13 ]
then
	echo "he/she is child"

elif [ $a -ge 13 -a $a -le 19 ]
then 
	echo "he/she is a teenager"
elif [ $a -ge 20 -a $a -le 59 ]
then
	echo "he/she is a adult"
elif [ $a -ge 60 ]
then 
	echo "he/she is oldage"
else
	echo "enter the valide age"
fi

